=== ekirkilevics/Magnolia/magnolia-core/src/main/resources/info/magnolia/cms/module/module.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- main definition -->
<!ELEMENT module (name, displayName?, class, version, description?, dependencies?, repositories?, servlets?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT displayName (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT class (#PCDATA)>

<!-- dependencies to other modules -->
<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency (name,version)>

<!-- servlet to register -->
<!ELEMENT servlets (servlet)>
<!ELEMENT servlet (class,mappings,name,comment?,params?)>
<!ELEMENT mapping (#PCDATA)>
<!ELEMENT mappings (mapping+)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT params (param*)>
<!ELEMENT param (name,value)>
<!ELEMENT value (#PCDATA)>

<!-- repositories to register -->
<!ELEMENT repositories (repository)>
<!ELEMENT repository (name,nodeTypeFile)>
<!ELEMENT nodeTypeFile EMPTY>

=== ekirkilevics/Magnolia/magnolia-module-mail/src/main/resources/META-INF/magnolia/mail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "module.dtd" >
<module>
    <name>mail</name>
    <class>info.magnolia.cms.mail.Engine</class>
    <version>3.0</version>
    <displayName>Magnolia templating mail</displayName>
    <servlets>
        <servlet>
            <class>info.magnolia.cms.mail.servlets.MgnlMailServlet</class>
            <mappings>
                <mapping>/Mail</mapping>
            </mappings>
            <name>Mail</name>
            <comment>Servlet to send email using the email system.</comment>
            <params>
                <!--              <param></param> -->
            </params>
        </servlet>
    </servlets>
</module>

=== ekirkilevics/Magnolia/magnolia-ui-vaadin-integration/src/main/resources/META-INF/magnolia/vaadin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
  <name>vaadin</name>
  <displayName>Magnolia Vaadin Module</displayName>
  <class>info.magnolia.ui.vaadin.integration.module.VaadinModule</class>
  <version>${project.version}</version>
  <dependencies>
    <dependency>
      <name>core</name>
      <version>5.0/*</version>
    </dependency>
  </dependencies>
</module>
