<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE License [
    <!ELEMENT License (Meta+)>
    <!ELEMENT Meta (VersionNumber,
                    Edition,
                    BuildNumber,
                    Provider,
                    ProviderAddress,
                    ProviderEmail,
                    ProductDomain)>
    <!ELEMENT VersionNumber (#PCDATA)>
    <!ELEMENT Edition (#PCDATA)>
    <!ELEMENT BuildNumber (#PCDATA)>
    <!ELEMENT Provider (#PCDATA)>
    <!ELEMENT ProviderAddress (#PCDATA)>
    <!ELEMENT ProviderEmail (#PCDATA)>
    <!ELEMENT ProductDomain (#PCDATA)>
]>
<License>
    <Meta>
        <VersionNumber>${magnolia.niceVersion}</VersionNumber>
        <Edition>${magnolia.edition}</Edition>
        <BuildNumber>${magnolia.releaseDate}</BuildNumber>
        <Provider>${pom.organization.name}</Provider>
        <ProviderAddress>
            <![CDATA[
Magnolia International Ltd.
Maiengasse 30
4056 Basel
Tel +41 61 228 9000
Switzerland
]]>
        </ProviderAddress>
        <ProviderEmail>info@magnolia.info</ProviderEmail>
        <ProductDomain>www.magnolia.info</ProductDomain>
    </Meta>
</License>