=== ekirkilevics/Magnolia/magnolia-core/src/main/resources/info/magnolia/module/model/module.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- main definition -->
<!ELEMENT module (name, (displayName|display-name)?,  description?, class?, versionHandler?, version, properties?, dependencies?, servlets?, repositories?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT displayName (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT versionHandler (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!-- deprecated : -->
<!ELEMENT display-name (#PCDATA)>

<!-- dependencies to other modules -->
<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency (name, version?, optional?)>
<!ELEMENT optional (#PCDATA)>

<!-- properties -->
<!ELEMENT properties (property+)>
<!ELEMENT property (name,value)>

<!-- servlet to register -->
<!ELEMENT servlets (servlet+)>
<!ELEMENT servlet (name, class, comment?, mappings, params?)>
<!ELEMENT mapping (#PCDATA)>
<!ELEMENT mappings (mapping+)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT params (param*)>
<!ELEMENT param (name,value)>

<!-- repositories to register -->
<!ELEMENT repositories (repository+)>
<!ELEMENT repository (name, workspaces, nodeTypeFile?)>
<!ELEMENT workspaces (workspace+)>
<!ELEMENT workspace (#PCDATA)>
<!ELEMENT nodeTypeFile (#PCDATA)>

=== ekirkilevics/Magnolia/magnolia-module-data/src/main/resources/META-INF/magnolia/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module SYSTEM "module.dtd">
<module>
	<name>data</name>
	<class>info.magnolia.module.data.DataModule</class>
	<version>3.0</version>
    <dependencies>
        <dependency>
            <name>adminInterface</name>
            <version>3.0</version>
        </dependency>
    </dependencies>
    <bootstrap-files>
        <bootstrap-file>config.modules.adminInterface.config.menu.data.xml</bootstrap-file>
    </bootstrap-files>
    <repositories>
        <repository>
            <name>magnolia</name>
			<workspaces>
				<workspace>data</workspace>
			</workspaces>
        </repository>
    </repositories>
</module>
