<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE License [
    <!ELEMENT License (Meta+)>
    <!ELEMENT Meta (VersionNumber,
                    BuildNumber,
                    Provider,
                    ProviderAddress,
                    ProviderEmail,
                    ProductDomain,
                    VersionPageHandle+)>
    <!ELEMENT VersionNumber (#PCDATA)>
    <!ELEMENT BuildNumber (#PCDATA)>
    <!ELEMENT Provider (#PCDATA)>
    <!ELEMENT ProviderAddress (#PCDATA)>
    <!ELEMENT ProviderEmail (#PCDATA)>
    <!ELEMENT ProductDomain (#PCDATA)>
    <!ELEMENT VersionPageHandle (#PCDATA)>]>



<License>
    <Meta>
        <VersionNumber>2.1 RC2</VersionNumber>
        <BuildNumber>$Revision$</BuildNumber>
        <Provider>obinary ltd</Provider>
        <ProviderAddress>magnolia organization llc&lt;br/&gt;Binningerstrasse 15 &lt;br/&gt;4051 Basel &lt;br/&gt;Tel +41 61 228 9000&lt;br/&gt;Switzerland</ProviderAddress>
        <ProviderEmail>info@magnolia.info</ProviderEmail>
        <ProductDomain>www.magnolia.info</ProductDomain>
        <VersionPageHandle>/redirects/version2-1.html</VersionPageHandle>
    </Meta>
    
</License>