<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Repositories [
  <!ELEMENT Repositories (Repository+)>
  <!ELEMENT Repository (RepositoryStore,StableWorkspace+)>
  <!ATTLIST Repository
    name CDATA #REQUIRED>
  <!ELEMENT RepositoryStore (FileSystem)>
  <!ELEMENT StableWorkspace (PersistenceManager,WorkspaceStore,BLOBStore?,DynamicWorkspace*)>
  <!ATTLIST StableWorkspace
    name CDATA #REQUIRED>
  <!ELEMENT PersistenceManager (param*)>
  <!ATTLIST PersistenceManager
    class CDATA #REQUIRED>
  <!ELEMENT WorkspaceStore (FileSystem)>
  <!ELEMENT BLOBStore (FileSystem)>
  <!ELEMENT DynamicWorkspace (FileSystem)>
  <!ELEMENT DynamicWorkspace (PersistenceManager,WorkspaceStore,BLOBStore?)>
  <!ATTLIST DynamicWorkspace
    name CDATA #REQUIRED>
  <!ELEMENT FileSystem (param*)>
  <!ATTLIST FileSystem
    class CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED>]>

<Repositories>

  <!--
  Website data store
    - Repository store
    - Workspaces (Dynamic / defaultStore / BLOBS)
  -->
  <Repository name="website">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
        <param name="path" value="../webapps/magnolia/repositories/website/repository"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/website/workspaces/default/data"/>
        </FileSystem>
      </WorkspaceStore>
      <BLOBStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/website/workspaces/default/blobs"/>
        </FileSystem>
      </BLOBStore>
      <!-- dynamic workspace based on main workspace -->
    </StableWorkspace>
  </Repository>




  <!--
  users data store
    - Repository store
    - Workspaces (Dynamic / defaultStore / BLOBS)
  -->
  <Repository name="users">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
        <param name="path" value="../webapps/magnolia/repositories/users/repository"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/users/workspaces/default/data"/>
        </FileSystem>
      </WorkspaceStore>
      <BLOBStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/users/workspaces/default/blobs"/>
        </FileSystem>
      </BLOBStore>
    </StableWorkspace>
  </Repository>




  <!--
  userRoles data store
    - Repository store
    - Workspaces (Dynamic / defaultStore / BLOBS)
  -->
  <Repository name="userroles">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
        <param name="path" value="../webapps/magnolia/repositories/userroles/repository"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/userroles/workspaces/default/data"/>
        </FileSystem>
      </WorkspaceStore>
      <BLOBStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/userroles/workspaces/default/blobs"/>
        </FileSystem>
      </BLOBStore>
    </StableWorkspace>
  </Repository>




  <!--
  config data store
    - Repository store
    - Workspaces (Dynamic / defaultStore / BLOBS)
  -->
  <Repository name="config">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
        <param name="path" value="../webapps/magnolia/repositories/config/repository"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/config/workspaces/default/data"/>
        </FileSystem>
      </WorkspaceStore>
      <BLOBStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="../webapps/magnolia/repositories/config/workspaces/default/blobs"/>
        </FileSystem>
      </BLOBStore>
    </StableWorkspace>
  </Repository>





  <!-- sample configuration for a repository that stores its state in a virtual file system -->
  <Repository name="cqfs">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.cq.CQFileSystem">
        <param name="path" value="${factory.home}/repositories/cqfs/repStore.dat"/>
        <param name="autoRepair" value="false"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.cq.CQFileSystem">
          <param name="path" value="${factory.home}/repositories/cqfs/workspaces/default/wspStore.dat"/>
          <param name="autoRepair" value="false"/>
        </FileSystem>
      </WorkspaceStore>
      <BLOBStore>
        <FileSystem class="org.apache.slide.jcr.fs.local.LocalFileSystem">
          <param name="path" value="${factory.home}/repositories/cqfs/workspaces/default/blobs"/>
        </FileSystem>
      </BLOBStore>
    </StableWorkspace>
  </Repository>

  <!-- sample configuration for a repository that stores its state on a WebDav server -->
  <Repository name="dav">
    <RepositoryStore>
      <FileSystem class="org.apache.slide.jcr.fs.dav.DavFileSystem">
        <param name="host" value="localhost"/>
        <param name="port" value="8080"/>
        <param name="path" value="/webdav/repository"/>
      </FileSystem>
    </RepositoryStore>
    <!-- main workspace -->
    <StableWorkspace name="default">
      <PersistenceManager class="org.apache.slide.jcr.core.state.xml.XMLPersistenceManager"/>
      <WorkspaceStore>
        <FileSystem class="org.apache.slide.jcr.fs.dav.DavFileSystem">
          <param name="host" value="localhost"/>
          <param name="port" value="8080"/>
          <param name="path" value="/webdav/workspaces/default"/>
        </FileSystem>
      </WorkspaceStore>
    </StableWorkspace>
  </Repository>
</Repositories>
