<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE Repository PUBLIC "-//The Apache Software Foundation//DTD Repository//EN" "file://config.dtd"> -->
<!DOCTYPE Repository [
<!--
    the Repository element configures a repository instance;
    individual workspaces of the repository are configured through
    separate configuration files called workspace.xml which are
    located in a subfolder of the workspaces root directory
    (see Workspaces element).

    it consists of

        a FileSystem element (the virtual file system
        used by the repository to persist global state such as
        registered namespaces, custom node types, etc..

        a Workspaces element that specifies to the location of
        workspaces root directory and the name of default workspace

        a Workspace element that is used as a workspace configuration
        template; it is used to create the initial workspace if there's
        no workspace yet and for creating additional workspaces through
        the api
-->
<!ELEMENT Repository (FileSystem,Workspaces,Workspace,Versioning)>

<!--
    a virtual file system
-->
<!ELEMENT FileSystem (param*)>
<!ATTLIST FileSystem
    class CDATA #REQUIRED>

<!--
    generic parameter (name/value pair)
-->
<!ELEMENT param EMPTY>
<!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED>

<!--
    the Workspaces element specifies the workspaces root directory
    (rootPath attribute) and the name of the default workspace
    (defaultWorkspace attribute).

    individual workspaces are configured through individual workspace.xml
    files located in a subfolder each of the workspaces root directory.
-->
<!ELEMENT Workspaces EMPTY>
<!ATTLIST Workspaces
    rootPath CDATA #REQUIRED
    defaultWorkspace CDATA #REQUIRED>

<!--
    the Workspace element serves as a workspace configuration template;
    it is used to create the initial workspace if there's no workspace yet
    and for creating additional workspaces through the api
-->
<!ELEMENT Workspace (FileSystem,PersistenceManager,SearchIndex?)>
<!ATTLIST Workspace
    name CDATA #REQUIRED>

<!--
    the PersistenceManager element configures the persistence manager
    to be used for the workspace; the class attribute specifies the
    FQN of the class implementing PersistenceManager interface
-->
<!ELEMENT PersistenceManager (param*)>
<!ATTLIST PersistenceManager
    class CDATA #REQUIRED>

<!--
    the SearchIndex element specifies the locaction of the search index
    (used by the QueryManager)
-->
<!ELEMENT SearchIndex (param*,FileSystem)>

<!--
the Versioning element specifies the location and persistence manager
that is used to store versions
    -->
<!ELEMENT Versioning (FileSystem, PersistenceManager)>
<!ATTLIST Versioning
rootPath CDATA #REQUIRED
>
]>
<Repository>
    <!--
        virtual file system where the repository stores global state
        (e.g. registered namespaces, custom node types, etc.)
    -->
    <FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
        <param name="path" value="../webapps/magnolia/repositories/website/repository"/>
    </FileSystem>
    <!--
        location of workspaces root directory and name of default workspace
    -->
    <Workspaces rootPath="../webapps/magnolia/repositories/website/workspaces" defaultWorkspace="default"/>
    <!--
        workspace configuration template:
        used to create the initial workspace if there's no workspace yet
    -->
    <Workspace name="default">
        <!--
            virtual file system of the workspace:
            class: FQN of class implementing FileSystem interface
        -->
        <FileSystem class="com.day.jackrabbit.fs.cq.CQFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/default.dat"/>
            <param name="autoRepair" value="false"/>
            <param name="blockSize" value="128"/>
            <param name="autoSync" value="true"/>
        </FileSystem>
        <!--
        <FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/default"/>
        </FileSystem>
        -->
        <!--
            persistence manager of the workspace:
            class: FQN of class implementing PersistenceManager interface
        -->
        <!--
        <PersistenceManager class="org.apache.jackrabbit.core.state.xml.XMLPersistenceManager"/>
        -->
        <!--
        <PersistenceManager class="org.apache.jackrabbit.core.state.mem.InMemPersistenceManager">
            <param name="initialCapacity" value="100000"/>
            <param name="loadFactor" value="0.3"/>
            <param name="persistent" value="true"/>
        </PersistenceManager>
        -->
        <PersistenceManager class="org.apache.jackrabbit.core.state.obj.ObjectPersistenceManager"/>
        <!--
            Search index and the file system it uses.
        -->
        <SearchIndex>
            <param name="useCompoundFile" value="true"/>
            <param name="minMergeDocs" value="1000"/>
            <param name="maxMergeDocs" value="10000"/>
            <param name="mergeFactor" value="10"/>

        <FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/index"/>
        </FileSystem>
        <!--
        <FileSystem class="com.day.jackrabbit.fs.cq.CQFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/index.dat"/>
            <param name="autoRepair" value="false"/>
            <param name="blockSize" value="128"/>
            <param name="autoSync" value="true"/>
        </FileSystem>
        -->

        </SearchIndex>
    </Workspace>

    <!--
        Configures the versioning
    -->
    <Versioning rootPath="../webapps/magnolia/repositories/website/version">
        <!--
            Configures the filesystem to use for versioning for the respective
            persistence manager
        -->
        <!--
        <FileSystem class="org.apache.jackrabbit.core.fs.local.LocalFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/version"/>
        </FileSystem>
		-->
        <FileSystem class="com.day.jackrabbit.fs.cq.CQFileSystem">
            <param name="path" value="../webapps/magnolia/repositories/website/workspaces/version.dat"/>
            <param name="autoRepair" value="false"/>
            <param name="blockSize" value="128"/>
            <param name="autoSync" value="true"/>
        </FileSystem>

        <!--
            Configures the perisistence manager to be used for persisting version state.
            Please note that the current versioning implementation is based on
            a 'normal' persistence manager, but this could change in future
            implementations.
        -->
        <!--
        <PersistenceManager class="org.apache.jackrabbit.core.state.mem.InMemPersistenceManager">
            <param name="initialCapacity" value="10000"/>
            <param name="loadFactor" value="0.3"/>
            <param name="persistent" value="false"/>
        </PersistenceManager>
        -->
        <PersistenceManager class="org.apache.jackrabbit.core.state.obj.ObjectPersistenceManager"/>

    </Versioning>

</Repository>
